#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
tabs -4
autoload -Uz promptinit
promptinit
prompt skwp

export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
export FC=gfortran

alias pacman='pacman --color=auto'
alias xbg='xbacklight -get'
alias xb='xbacklight -set'
alias l='llpp'
alias less='less -x4'
alias lu='killall -SIGHUP llpp'
alias emacs='emacs -nw'
alias p='pygmentize -O style=monokai'
alias z='zathura'
unalias gs

function pl {
    p $1 | less -R
}

bindkey '^R' history-incremental-search-backward
bindkey '^H' backward-kill-word
export EDITOR=vim
export GOPATH=${HOME}/go

# Nix
if [ -e ${HOME}/.nix-profile/etc/profile.d/nix.sh ]
then
    source ${HOME}/.nix-profile/etc/profile.d/nix.sh
fi
if [ -d ${HOME}/.nix-profile/lib/pkgconfig ]
then
    export PKG_CONFIG_PATH=${HOME}/.nix-profile/lib/pkgconfig:${PKG_CONFIG_PATH}
fi
export LD_LIBRARY_PATH=${HOME}/.nix-profile/lib:${LD_LIBRARY_PATH}

# Thefuck
eval $(thefuck --alias)

# direnv
eval "$(direnv hook zsh)"
