#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
tabs -4
autoload -Uz promptinit
promptinit
prompt skwp

alias xbg='xbacklight -get'
alias xb='xbacklight -set'
alias l='llpp'
alias lu='killall -SIGHUP llpp'

bindkey '^R' history-incremental-search-backward
bindkey '^H' backward-kill-word
export EDITOR=vim
